name: Run TOX tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: "3.6"
            env: TOXENV=py36-django22
          - python-version: "3.7"
            env: TOXENV=py37-django22
          - python-version: "3.8"
            env: TOXENV=py38-django22
          - python-version: "3.8"
            env: TOXENV=py38-django30
          - python-version: "3.6"
            env: TOXENV=py36-django31
          - python-version: "3.7"
            env: TOXENV=py37-django31
          - python-version: "3.8"
            env: TOXENV=py38-django31
          - python-version: "3.7"
            env: TOXENV=py37-django32
          - python-version: "3.8"
            env: TOXENV=py38-django32
          - python-version: "3.8"
            env: TOXENV=lint

    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Install Dependancies
        run: |
          sudo apt-get update
          sudo apt-get install slapd ldap-utils build-essential python3-dev libldap2-dev libsasl2-dev slapd ldap-utils lcov
          python -m pip install --upgrade pip
          pip install tox

      - name: Run TOX Tests.
        run: tox
